### ISSUE TITLE
absence of lib.js

### ISSUE THREAD

**Issue by cao1034** [vacuumlabs/cardano-crypto.js#13]
npm install && npm run test 
Error:
> cardano-crypto.js@5.3.0 test /Users/xbc/Desktop/ADA/cardano-crypto.js-master
> tape test/**/*.js

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module './lib.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/xbc/Desktop/ADA/cardano-crypto.js-master/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

**Comment by refi93** [comment]
I assume you were trying to run the tests right after cloning the github repo. The github repo does not contain the compiled javascipt, i.e. lib.js. You need to transpile the c source files in `vendor/cbits` with emscripten: https://github.com/vacuumlabs/cardano-crypto.js#development

**Comment by refi93** [comment]
Or you can download the package from npm (https://www.npmjs.com/package/cardano-crypto.js) and copy from there lib.js if you don't want to modify it
